### PR TITLE
Short mention of bevy-godot integration

### PR DESCRIPTION
**Pull request by Bromeon**
@rand0m-cloud I thought I'd mention your integration on the page 🙂 

I looked at the examples, but it looks like they are spread across multiple files. Is there something like a "Hello World" which is roughly 20-30 LoC, in the same style that the other integrations mention?

### CODE REVIEW

**Comment by rand0m-cloud** [comment]
I think this is the smallest example I can make, it demonstrates enough ECS to spark people's interest.

```rust
use bevy_godot::prelude::*;

fn init(_handle: &InitHandle) {}
fn build_app(app: &mut App) {
    app.add_startup_system(spawn_cube).add_system(move_cube);
}

bevy_godot_init!(init, build_app);

#[derive(Component)]
pub struct Cube {
    starting_position: Vector2,
}

fn spawn_cube(mut commands: Commands) {
    let starting_position = Vector2::new(500.0, 300.0);
    commands
        .spawn()
        .insert(GodotScene::from_path("res://simple_scene.tscn"))
        .insert(Cube { starting_position })
        .insert(Transform2D::from(
            GodotTransform2D::from_scale_rotation_origin(Vector2::ONE, 0.0, starting_position),
        ));
}

fn move_cube(mut cube: Query<(&Cube, &mut Transform2D)>, time: Res<Time>) {
    let (cube, mut transform) = cube.single_mut();
    transform.origin =
        Vector2::RIGHT * 300.0 * time.seconds_since_startup().sin() as f32 + cube.starting_position;
}
```

**Comment by Bromeon** [comment]
Thanks a lot! 🙂 

I added you as `Co-authored-by:`. Let me know if you're happy with this commit.

**Comment by rand0m-cloud** [comment]
LGTM! Thank you for including my library in the book! 🚀

**Comment by Bromeon** [comment]
Thanks a lot to _you_ for contributing to the godot-rust ecosystem! ❤️

**Pull request merged**
