### PR TITLE
Tutorial for using classes as reference.

### PR DESCRIPTION
**Pull request by astrale-sharp**
#45

### CODE REVIEW

**Comment by Bromeon** [comment]
Hello,

Please submit pull requests only with significant content. Blank sections are not interesting. On the other hand, they make management and review of issues and PRs more complex for us, as it takes time to review, check merge conflicts, etc.

I'll leave this open; please force-push your next changes into this PR and do not open yet another one.
Thanks for the understanding!

**Comment by jacobsky** [comment]
As this PR doesn't appear to add anything yet, I am going to go ahead and close this for the time being. Perhaps once #50 is completed, we can either reopen this PR once there's a little more progress or create a new PR all together.

**Comment by astrale-sharp** [comment]
I'd like to use this PR to work on #45, can it be reopen (as draft ) if thats okay @Bromeon .

**Comment by Bromeon** [comment]
Good with me. Since you deleted the branch, I can't reopen it anymore, so you might need to go through the procedure again 😬

**Comment by astrale-sharp** [comment]
oh no ! git has come for its revenge xD

**Comment by astrale-sharp** [comment]
Edit I'm back from hell, the branch is live but its content is not of value yet, i have to wait for the PR to be opened again to force push in there otherwise the PR cant be opened, let me know if this works!

**Comment by jacobsky** [comment]
@astrale-sharp That would be fine with me. Feel free to reopen this PR with the old branch whenever you are ready for another try.

**Comment by astrale-sharp** [comment]
Good! We'll I dont think i have the proper clearance to reopen it myself unfortunately!

**Comment by Bromeon** [comment]
Try https://github.com/godot-rust/book/pull/47 😬
(push to existing branch)

Honestly, GitHub is weird sometimes. It should be possible to assign a new branch to an existing PR.

**Pull request closed without merging**
